### ISSUE TITLE
Startseite implementieren

### ISSUE THREAD

**Issue by emanuel-metzenthin** [schul-cloud/schulcloud-content-editor#13]
Es soll eine Startseite geben, auf der Informationen wie bspw. die Items mit den höchsten Klickzahlen angezeigt werden.

**Comment by adrianjost** [comment]
@kremer-io Wenn wir die Suchseite als Startseite nutzen wollen brauchen wir das doch nicht mehr oder? Zumal es ja eine eigene Statistikseite geben soll.
https://github.com/schul-cloud/schulcloud-content-editor/issues/18
