### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by emanuel-metzenthin** [schul-cloud/schulcloud-content-editor#19]
Content Items sollen gefiltert werden können:

- [x] Erstellungsdatum
- [ ] Feature Datum
- [x] Provider 
- [ ] nonOER
- [ ] Metadaten
- [x] (leichte Erweiterbarkeit zum Hinzufügen neuer Filter)

update: filter sollten API nutzen, da sonst nur die wenigen bereits geladenen Werte aktualisiert werden. Codebeispiele siehe pagination im search-modul und [hier](https://github.com/schul-cloud/schulcloud-client/blob/master/controllers/content.js)

**Comment by adrianjost** [comment]
https://github.com/schul-cloud/schulcloud-content-editor/wiki/add-new-filter
